openapi: 3.0.3
info:
  title: DIYML - Analyze Model API
  description: This is the post request endpoint for the analyze model feature of DIYML.
  version: 1.0.0
paths:
  /analyze_model:
    post:
      tags:
        - Analyze Model
      summary: Analyze model statistics.
      description: Analyze model statistics.
      operationId: analyzeModel
      requestBody:
        description: Analyze model statistics.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProjectReference'
        required: true
      responses:
        '200':
          description: Successful login.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnalysisResults'
        '400':
          description: Invalid parameters supplied.
        '404':
          description: Could not locate project.


components:
  schemas:
    ProjectReference:
      type: object
      properties:
        project_name:
          type: string
          example: ExampleProjectName
        api_token:
          type: string
          example: exampleAPItoken189769!
    AnalysisResults:
      type: object
      properties:
        project_name: 
          type: string
          example: ExampleProjectName
        results:
          type: string
          example: ResultsString
    