openapi: 3.0.3
info:
  title: DIYML - Reports API
  description: The endpoint for reporting on a model.
  version: 1.0.0
paths:
  /reporting:
    post:
      tags:
        - Reports
      summary: Generate report statistics for a model.
      description: Generate report statistics for a model.
      operationId: publishModel
      requestBody:
        description: Generate report statistics for a model.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReportRequest'
        required: true
      responses:
        '200':
          description: Successful report generation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReportResponse'
        '400':
          description: Invalid parameters supplied.
        '403':
          description: Invalid project for reporting.
        '404':
          description: Could not locate project.


components:
  schemas:
    ReportRequest:
      type: object
      properties:
        project_name:
          type: string
          example: ExampleProjectName
        api_token:
          type: string
          example: exampleAPItoken189769!
        image_data:
          type: string
          example: 921387469182374IMAGEBYTE9278316498712346
    ReportResponse:
      type: object
      properties:
        report_results:
          type: string
          example: results from reporting
    